name: Deploy to AWS (release)
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::rmarkdown
            any::knitr
            any::ggplot2
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Build
        uses: quarto-dev/quarto-actions/render@v2
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::442430797903:role/n2g-recipes-2024-claude-apps-com-UploadRole-MY8Db4LV3ygW
      - name: Deploy
        run: aws s3 sync --delete --exclude=beta/\* --content-encoding utf8 _site s3://n2g-recipes-2024.claude-apps.com/website/
